<a href="https://colab.research.google.com/github/Sairaj-2112/Barter/blob/main/Web_Analytics_and_Applications_27_Mar_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# **UNIT V: Web Analytics and Applications**

## **Session Flow (2 Hours Interactive Class)**

---

## **Session Objective**

By the end of this session, you will:

* Understand how modern websites analyze user behavior
* Learn how recommendation systems work in real-world platforms
* Explore tools used for large-scale web analytics
* Experience hands-on implementation of key concepts

---

## **Session Structure Overview**

This session is divided into:

* Conceptual understanding
* Real-world industry examples
* Guided hands-on activities

---

## **Phase 1: Introduction and Industry Context (0 – 10 Minutes)**

### What we will cover:

* What is Web Analytics?
* What is Web Mining?
* Why companies rely heavily on user data

### Industry Connection:

* How platforms like Amazon and Netflix understand user behavior

---

## **Phase 2: Web Personalization (10 – 30 Minutes)**

### Topics:

* Adaptive websites
* User profiling

### What you will learn:

* How websites customize content for each user
* How user behavior is converted into a digital profile

### Hands-on Activity:

* Build a simple user profile from browsing data

---

## **Phase 3: Recommender Systems (30 – 70 Minutes)**

---

### Part 1: Content-Based Filtering (30 – 45 Minutes)

#### What you will learn:

* How systems recommend items similar to your interests

#### Hands-on Activity:

* Build a simple similarity-based recommendation system

---

### Part 2: Collaborative Filtering (45 – 60 Minutes)

#### What you will learn:

* How platforms use behavior of similar users

#### Hands-on Activity:

* Identify similar users using interaction data

---

### Part 3: Hybrid Recommendation Systems (60 – 70 Minutes)

#### What you will learn:

* Why real-world systems combine multiple approaches
* How platforms like Netflix improve accuracy

---

## **Phase 4: Web Analytics Tools and Frameworks (70 – 90 Minutes)**

---

### Google Analytics

#### What you will learn:

* How website traffic is tracked
* Key metrics such as users, sessions, and bounce rate

---

### Hadoop and Spark

#### What you will learn:

* Why big data tools are required
* How large-scale user data is processed in industry

---

## **Phase 5: Emerging Trends in Web Mining (90 – 110 Minutes)**

---

### Social Media Analytics

#### What you will learn:

* How platforms analyze user behavior on social media
* Trend detection and user engagement

---

### Opinion Mining (Sentiment Analysis)

#### What you will learn:

* How systems understand user opinions from text

#### Hands-on Activity:

* Analyze sentiment of sample text data

---

### Web Mining for Cybersecurity

#### What you will learn:

* Basics of phishing detection
* How anomalies are detected in web data

---

## **Phase 6: Applications and Real-World Use Cases (110 – 120 Minutes)**

---

### Domains Covered:

* E-commerce analytics
* Customer behavior prediction
* Healthcare analytics

---

## **Final Takeaways**

* Personalization improves user experience
* Recommendation systems drive engagement
* Analytics tools help measure and optimize performance
* Emerging trends are shaping the future of intelligent systems

---

## **How This Session Will Run**

* Interactive explanations
* Real-world examples from industry
* Guided hands-on exercises
* Open discussion and questions

---

## **Expectation from Participants**

* Basic understanding of programming is helpful
* Active participation during hands-on activities
* Asking questions during the session

---

In [ ]:
# Have you ever opened Amazon or Netflix…
# and felt like it already knows what you want?

# You didn’t search for it…
# but somehow, it shows exactly what you were thinking about.

# How many of you have experienced this?

In [ ]:
# What is Web Analytics?
# Web Analytics is the process of:
# Collecting, measuring, analyzing, and interpreting data about how users interact with a website.

# Think about an e-commerce website like Amazon:
# How many users visited today?
# Which product was viewed the most?
# How many users added items to cart but didn’t purchase?
# All this information comes from Web Analytics.

# Tools / Technologies Used
# Google Analytics
# Adobe Analytics
# Python (Pandas, Matplotlib)
# Big Data tools (Hadoop, Spark)

# Advantages
# Data-driven decision making
# Better user experience
# Helps increase revenue

# Limitations
# Privacy concerns (cookies, tracking)
# Data can be misleading if interpreted incorrectly
# Requires proper setup and expertise

In [ ]:
# What is Web Mining?

# Web Mining is the process of:
# Extracting useful patterns, knowledge, and insights from web data.

# Consider platforms like Amazon or Netflix:
# How do they know what you might like next?
# How do they understand trends across millions of users?
# They use Web Mining to analyze massive amounts of web data and discover patterns.

In [ ]:
# Types of Web Mining

# 1. Web Content Mining
# Extracting information from web pages
# Example: Text, images, videos

# 2. Web Structure Mining
# Analyzing how web pages are linked
# Example: Google ranking using links

# 3. Web Usage Mining
# Understanding user behavior
# Example: Click patterns, navigation paths

# Tools / Technologies Used
# Python (BeautifulSoup, Scrapy)
# Machine Learning libraries (Scikit-learn)
# Big Data tools (Hadoop, Spark)
# NLP tools for text analysis

# Use Cases
# Recommendation systems
# Fraud detection
# Customer segmentation
# Search engine optimization
# Social media trend analysis

# Advantages
# Extracts valuable insights from large data
# Helps in decision-making
# Enables automation and prediction

# Limitations
# Data privacy issues
# Noisy and unstructured data
# High computational cost

| Aspect  | Web Analytics           | Web Mining                  |
| ------- | ----------------------- | --------------------------- |
| Focus   | Measuring user behavior | Discovering hidden patterns |
| Goal    | Reporting & tracking    | Prediction & intelligence   |
| Example | Page views, bounce rate | Recommendation systems      |

In [ ]:
# Why Companies Rely Heavily on User Data?

# User data = Business power


# Platforms like Amazon and Netflix do NOT guess…
# They use data to:
# Recommend products or content
# Personalize the entire experience
# Increase engagement and revenue

# What Kind of User Data is Collected?
# What you search
# What you click
# How long you stay
# What you buy or watch
# When you leave

# Why This is Critical for Companies
# 1. Personalization
# Every user gets a customized experience
# 2. Increased Revenue
# More relevant products → Higher sales
# 3. Customer Retention
# Better experience → Users stay longer
# 4. Competitive Advantage
# Data-driven companies outperform others

In [ ]:
# Phase 2: Web Personalization (Adaptive Websites)

# Let’s start with a question:
# “Why does the same website look different for different users?”
# That is because of Adaptive Websites.
# Adaptive websites dynamically change their content, layout, or recommendations based on the user.

# What is an Adaptive Website?
# An adaptive website is one that:
# Shows different content to different users
# Changes based on:
# User behavior
# Preferences
# Location
# Device

# Take Amazon:
# User A sees:
# Electronics recommendations
# User B sees:
# Clothing and fashion items
# Same website, completely different experience

# Tools / Technologies Used
# Web tracking tools
# Google Analytics
# Python (Pandas, Scikit-learn)
# Big Data tools (Spark, Hadoop)

In [ ]:
# Phase 2: Web Personalization (User Profiling)

# Let’s begin with a simple question:
# “How does a website remember what you like?”
# The answer is User Profiling.

# User profiling is the process of creating a digital representation of a user based on their behavior, preferences, and interactions.

In [ ]:
# What is a Digital Profile?

# A digital profile contains:
# Interests (e.g., sports, movies, electronics)
# Behavior patterns
# Preferences
# Activity history

# On Amazon:
# If you:
# Search for laptops
# Compare prices
# Read reviews
# Your profile becomes:
# “User interested in electronics”

In [ ]:
# Problem Statement
# We have user browsing logs from a website.
# Our goal is to convert raw activity into a meaningful user profile
# that can be used for personalization and recommendation.

# Step 1:
import pandas as pd

data = pd.DataFrame({
    "user_id": [101,101,101,102,102,103,103,103,103],
    "timestamp": [
        "2026-03-20 10:00","2026-03-20 10:05","2026-03-20 10:10",
        "2026-03-20 11:00","2026-03-20 11:10",
        "2026-03-20 12:00","2026-03-20 12:05","2026-03-20 12:10","2026-03-20 12:20"
    ],
    "page_category": [
        "Electronics","Electronics","Accessories",
        "Fashion","Fashion",
        "Electronics","Mobiles","Mobiles","Accessories"
    ],
    "time_spent_sec": [60,120,40,200,150,80,100,120,60]
})

data["timestamp"] = pd.to_datetime(data["timestamp"])

data

   user_id           timestamp page_category  time_spent_sec
0      101 2026-03-20 10:00:00   Electronics              60
1      101 2026-03-20 10:05:00   Electronics             120
2      101 2026-03-20 10:10:00   Accessories              40
3      102 2026-03-20 11:00:00       Fashion             200
4      102 2026-03-20 11:10:00       Fashion             150
5      103 2026-03-20 12:00:00   Electronics              80
6      103 2026-03-20 12:05:00       Mobiles             100
7      103 2026-03-20 12:10:00       Mobiles             120
8      103 2026-03-20 12:20:00   Accessories              60

In [ ]:
# Step 2: Feature Engineering (Industry Thinking)

# Feature 1: Total Time Spent per Category
category_time = data.groupby(["user_id","page_category"])["time_spent_sec"].sum().unstack(fill_value=0)

category_time

page_category  Accessories  Electronics  Fashion  Mobiles
user_id
101                     40          180        0        0
102                      0            0      350        0
103                     60           80        0      220

In [ ]:
# Feature 2: Number of Visits per Category

category_visits = data.groupby(["user_id","page_category"]).size().unstack(fill_value=0)

category_visits

page_category  Accessories  Electronics  Fashion  Mobiles
user_id
101                      1            2        0        0
102                      0            0        2        0
103                      1            1        0        2

In [ ]:
# Step 3: Combine Features into User Profile

user_profile = category_time.add_suffix("_time").join(
    category_visits.add_suffix("_visits")
)

user_profile

page_category,Accessories_time,Electronics_time,Fashion_time,Mobiles_time,Accessories_visits,Electronics_visits,Fashion_visits,Mobiles_visits
user_id,,,,,,,,
101,40,180,0,0,1,2,0,0
102,0,0,350,0,0,0,2,0
103,60,80,0,220,1,1,0,2

In [ ]:
# Step 4: Normalize to Get Interest Scores

normalized_profile = category_time.div(category_time.sum(axis=1), axis=0)

normalized_profile

page_category  Accessories  Electronics  Fashion   Mobiles
user_id
101               0.181818     0.818182      0.0  0.000000
102               0.000000     0.000000      1.0  0.000000
103               0.166667     0.222222      0.0  0.611111

In [ ]:
# Step 5: Identify Dominant Interest (Key Industry Insight)

user_profile["top_interest"] = normalized_profile.idxmax(axis=1)

user_profile

page_category,Accessories_time,Electronics_time,Fashion_time,Mobiles_time,Accessories_visits,Electronics_visits,Fashion_visits,Mobiles_visits,top_interest
user_id,,,,,,,,,
101,40,180,0,0,1,2,0,0,Electronics
102,0,0,350,0,0,0,2,0,Fashion
103,60,80,0,220,1,1,0,2,Mobiles

In [ ]:
# Hands-on: User Profiling using PySpark (Big Data Level)

!pip install pyspark -q

In [ ]:
# Step 1: Initialize Spark Session

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("UserProfilingPipeline") \
    .getOrCreate()

spark

In [ ]:
# Step 2:

from pyspark.sql import Row
from pyspark.sql.functions import col

data = [
    Row(user_id=101, timestamp="2026-03-20 10:00:00", category="Electronics", time_spent=60),
    Row(user_id=101, timestamp="2026-03-20 10:05:00", category="Electronics", time_spent=120),
    Row(user_id=101, timestamp="2026-03-20 10:10:00", category="Accessories", time_spent=40),

    Row(user_id=102, timestamp="2026-03-20 11:00:00", category="Fashion", time_spent=200),
    Row(user_id=102, timestamp="2026-03-20 11:10:00", category="Fashion", time_spent=150),

    Row(user_id=103, timestamp="2026-03-20 12:00:00", category="Electronics", time_spent=80),
    Row(user_id=103, timestamp="2026-03-20 12:05:00", category="Mobiles", time_spent=100),
    Row(user_id=103, timestamp="2026-03-20 12:10:00", category="Mobiles", time_spent=120),
    Row(user_id=103, timestamp="2026-03-20 12:20:00", category="Accessories", time_spent=60),
]

df = spark.createDataFrame(data)

df.show()

+-------+-------------------+-----------+----------+
|user_id|          timestamp|   category|time_spent|
+-------+-------------------+-----------+----------+
|    101|2026-03-20 10:00:00|Electronics|        60|
|    101|2026-03-20 10:05:00|Electronics|       120|
|    101|2026-03-20 10:10:00|Accessories|        40|
|    102|2026-03-20 11:00:00|    Fashion|       200|
|    102|2026-03-20 11:10:00|    Fashion|       150|
|    103|2026-03-20 12:00:00|Electronics|        80|
|    103|2026-03-20 12:05:00|    Mobiles|       100|
|    103|2026-03-20 12:10:00|    Mobiles|       120|
|    103|2026-03-20 12:20:00|Accessories|        60|
+-------+-------------------+-----------+----------+

In [ ]:
# Step 3: Convert Timestamp to Proper Format

from pyspark.sql.functions import to_timestamp

df = df.withColumn("timestamp", to_timestamp("timestamp"))

df.printSchema()

root
 |-- user_id: long (nullable = true)
 |-- timestamp: timestamp (nullable = true)
 |-- category: string (nullable = true)
 |-- time_spent: long (nullable = true)

In [ ]:
# Step 4: Feature Engineering

# Feature 1: Total Time Spent per Category
from pyspark.sql.functions import sum as spark_sum

category_time = df.groupBy("user_id", "category") \
    .agg(spark_sum("time_spent").alias("total_time"))

category_time.show()

+-------+-----------+----------+
|user_id|   category|total_time|
+-------+-----------+----------+
|    102|    Fashion|       350|
|    101|Electronics|       180|
|    101|Accessories|        40|
|    103|Accessories|        60|
|    103|Electronics|        80|
|    103|    Mobiles|       220|
+-------+-----------+----------+

In [ ]:
# Feature 2: Number of Visits

from pyspark.sql.functions import count

category_visits = df.groupBy("user_id", "category") \
    .agg(count("*").alias("visit_count"))

category_visits.show()

+-------+-----------+-----------+
|user_id|   category|visit_count|
+-------+-----------+-----------+
|    102|    Fashion|          2|
|    101|Electronics|          2|
|    101|Accessories|          1|
|    103|Accessories|          1|
|    103|Electronics|          1|
|    103|    Mobiles|          2|
+-------+-----------+-----------+

In [ ]:
# Step 5: Combine Features

user_features = category_time.join(
    category_visits,
    on=["user_id", "category"]
)

user_features.show()

+-------+-----------+----------+-----------+
|user_id|   category|total_time|visit_count|
+-------+-----------+----------+-----------+
|    102|    Fashion|       350|          2|
|    101|Electronics|       180|          2|
|    101|Accessories|        40|          1|
|    103|Accessories|        60|          1|
|    103|Electronics|        80|          1|
|    103|    Mobiles|       220|          2|
+-------+-----------+----------+-----------+

In [ ]:
# Step 6: Normalize (Interest Score)

from pyspark.sql.window import Window
from pyspark.sql.functions import sum as spark_sum

window_spec = Window.partitionBy("user_id")

user_features = user_features.withColumn(
    "total_user_time",
    spark_sum("total_time").over(window_spec)
)

user_features = user_features.withColumn(
    "interest_score",
    col("total_time") / col("total_user_time")
)

user_features.show()

+-------+-----------+----------+-----------+---------------+-------------------+
|user_id|   category|total_time|visit_count|total_user_time|     interest_score|
+-------+-----------+----------+-----------+---------------+-------------------+
|    101|Electronics|       180|          2|            220| 0.8181818181818182|
|    101|Accessories|        40|          1|            220|0.18181818181818182|
|    102|    Fashion|       350|          2|            350|                1.0|
|    103|Accessories|        60|          1|            360|0.16666666666666666|
|    103|Electronics|        80|          1|            360| 0.2222222222222222|
|    103|    Mobiles|       220|          2|            360| 0.6111111111111112|
+-------+-----------+----------+-----------+---------------+-------------------+